security:
    enable_authenticator_manager: true

    firewalls:
        main:
            custom_authenticators:
                - App\Security\ApiTokenAuthenticator

    access_control:
        - { path: ^/languages, roles: ROLE_READ, methods: [GET] }
        - { path: ^/translation-keys, roles: ROLE_READ, methods: [GET] }
        - { path: ^/translation-keys, roles: ROLE_WRITE, methods: [POST, PUT, DELETE] }
        - { path: ^/translations, roles: ROLE_READ, methods: [GET] }
        - { path: ^/translations, roles: ROLE_WRITE, methods: [POST, PUT, DELETE] }
