security:
    enable_authenticator_manager: true

    firewalls:
        main:
            custom_authenticators:
                - App\Security\ApiTokenAuthenticator

    access_control:
        - { path: ^/languages, roles: ROLE_READ }
